<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Models\LaboratoryInventory;

class LaboratoryInventorySeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing laboratory inventory first
        DB::table('laboratory_inventory')->delete();

        // Comprehensive MISD laboratory inventory
        $inventoryItems = [
            // MISD Computer Laboratory 1 Inventory
            [
                'laboratory_id' => 1,
                'asset_tag' => 'MISD-LAB1-001',
                'computer_name' => 'MISD-LAB1-PC001',
                'lab_pc_num' => 'LAB1-001',
                'category' => 'Desktop',
                'processor' => 'Intel Core i5-12400',
                'motherboard' => 'Dell OptiPlex 7090',
                'video_card' => 'Intel UHD Graphics 730',
                'dvd_rom' => null,
                'psu' => '260W',
                'ram' => '16GB DDR4',
                'storage' => '512GB NVMe SSD',
                'serial_number' => 'DL-MISD-LAB1-001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Main workstation for programming exercises',
                'deployment_date' => '2023-01-15',
                'last_maintenance' => '2024-01-15',
            ],
            [
                'laboratory_id' => 1,
                'asset_tag' => 'MISD-LAB1-002',
                'computer_name' => 'MISD-LAB1-PC002',
                'lab_pc_num' => 'LAB1-002',
                'category' => 'Desktop',
                'processor' => 'Intel Core i5-12400',
                'motherboard' => 'Dell OptiPlex 7090',
                'video_card' => 'Intel UHD Graphics 730',
                'dvd_rom' => null,
                'psu' => '260W',
                'ram' => '16GB DDR4',
                'storage' => '512GB NVMe SSD',
                'serial_number' => 'DL-MISD-LAB1-002',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Main workstation for programming exercises',
                'deployment_date' => '2023-01-15',
                'last_maintenance' => '2024-01-15',
            ],
            [
                'laboratory_id' => 1,
                'asset_tag' => 'MISD-LAB1-003',
                'computer_name' => 'MISD-LAB1-PC003',
                'lab_pc_num' => 'LAB1-003',
                'category' => 'Desktop',
                'processor' => 'Intel Core i5-12400',
                'motherboard' => 'Dell OptiPlex 7090',
                'video_card' => 'Intel UHD Graphics 730',
                'dvd_rom' => null,
                'psu' => '260W',
                'ram' => '16GB DDR4',
                'storage' => '512GB NVMe SSD',
                'serial_number' => 'DL-MISD-LAB1-003',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Main workstation for programming exercises',
                'deployment_date' => '2023-01-15',
                'last_maintenance' => '2024-01-15',
            ],
            [
                'laboratory_id' => 1,
                'asset_tag' => 'MISD-LAB1-004',
                'computer_name' => 'MISD-LAB1-PC004',
                'lab_pc_num' => 'LAB1-004',
                'category' => 'Desktop',
                'processor' => 'Intel Core i5-12400',
                'motherboard' => 'Dell OptiPlex 7090',
                'video_card' => 'Intel UHD Graphics 730',
                'dvd_rom' => null,
                'psu' => '260W',
                'ram' => '16GB DDR4',
                'storage' => '512GB NVMe SSD',
                'serial_number' => 'DL-MISD-LAB1-004',
                'status' => 'Under Repair',
                'condition' => 'Fair',
                'notes' => 'Power supply issues',
                'deployment_date' => '2023-01-15',
                'last_maintenance' => '2024-01-15',
                'repair_start_date' => '2025-02-01',
                'repair_description' => 'PSU replacement needed',
                'repaired_by' => 'MISD Technical Support',
            ],

            // MISD Computer Laboratory 2 Inventory
            [
                'laboratory_id' => 2,
                'asset_tag' => 'MISD-LAB2-001',
                'computer_name' => 'MISD-LAB2-PC001',
                'lab_pc_num' => 'LAB2-001',
                'category' => 'Desktop',
                'processor' => 'Intel Core i7-12700',
                'motherboard' => 'HP EliteDesk 800 G6',
                'video_card' => 'NVIDIA GeForce RTX 3060',
                'dvd_rom' => null,
                'psu' => '300W',
                'ram' => '32GB DDR4',
                'storage' => '1TB NVMe SSD',
                'serial_number' => 'HP-MISD-LAB2-001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Advanced programming workstation',
                'deployment_date' => '2023-06-20',
                'last_maintenance' => '2024-06-20',
            ],
            [
                'laboratory_id' => 2,
                'asset_tag' => 'MISD-LAB2-002',
                'computer_name' => 'MISD-LAB2-PC002',
                'lab_pc_num' => 'LAB2-002',
                'category' => 'Desktop',
                'processor' => 'Intel Core i7-12700',
                'motherboard' => 'HP EliteDesk 800 G6',
                'video_card' => 'NVIDIA GeForce RTX 3060',
                'dvd_rom' => null,
                'psu' => '300W',
                'ram' => '32GB DDR4',
                'storage' => '1TB NVMe SSD',
                'serial_number' => 'HP-MISD-LAB2-002',
                'status' => 'Deployed',
                'condition' => 'Good',
                'notes' => 'Advanced programming workstation',
                'deployment_date' => '2023-06-20',
                'last_maintenance' => '2024-06-20',
            ],

            // MISD Systems Laboratory Inventory
            [
                'laboratory_id' => 3,
                'asset_tag' => 'MISD-SYS-001',
                'computer_name' => 'MISD-SYS-SRV001',
                'lab_pc_num' => 'SYS-001',
                'category' => 'Server',
                'processor' => 'Intel Xeon Silver 4210R',
                'motherboard' => 'Dell PowerEdge R740',
                'video_card' => 'Matrox G200eR3',
                'dvd_rom' => null,
                'psu' => '750W Redundant',
                'ram' => '64GB DDR4 ECC',
                'storage' => '2x 1TB SAS HDD RAID 1',
                'serial_number' => 'DL-MISD-SYS-SV001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Database server for training',
                'deployment_date' => '2023-03-10',
                'last_maintenance' => '2024-03-10',
            ],
            [
                'laboratory_id' => 3,
                'asset_tag' => 'MISD-SYS-002',
                'computer_name' => 'MISD-SYS-SRV002',
                'lab_pc_num' => 'SYS-002',
                'category' => 'Server',
                'processor' => 'Intel Xeon Silver 4210R',
                'motherboard' => 'Dell PowerEdge R740',
                'video_card' => 'Matrox G200eR3',
                'dvd_rom' => null,
                'psu' => '750W Redundant',
                'ram' => '64GB DDR4 ECC',
                'storage' => '4x 2TB SAS HDD RAID 10',
                'serial_number' => 'DL-MISD-SYS-SV002',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Application server for training',
                'deployment_date' => '2023-03-10',
                'last_maintenance' => '2024-03-10',
            ],

            // MISD Network Laboratory Inventory
            [
                'laboratory_id' => 4,
                'asset_tag' => 'MISD-NET-001',
                'computer_name' => 'MISD-NET-RT001',
                'lab_pc_num' => 'NET-001',
                'category' => 'Server',
                'processor' => 'Intel Xeon D-1521',
                'motherboard' => 'Cisco ISR 4321',
                'video_card' => null,
                'dvd_rom' => null,
                'psu' => 'Internal PSU',
                'ram' => '4GB DDR3',
                'storage' => '8GB Flash',
                'serial_number' => 'CS-MISD-NET-RT001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Router for networking labs',
                'deployment_date' => '2023-04-05',
                'last_maintenance' => '2024-04-05',
            ],
            [
                'laboratory_id' => 4,
                'asset_tag' => 'MISD-NET-002',
                'computer_name' => 'MISD-NET-FW001',
                'lab_pc_num' => 'NET-002',
                'category' => 'Server',
                'processor' => 'Intel Celeron J3455',
                'motherboard' => 'Fortinet FortiGate 60F',
                'video_card' => null,
                'dvd_rom' => null,
                'psu' => 'External Adapter',
                'ram' => '2GB DDR3',
                'storage' => '16GB Flash',
                'serial_number' => 'FT-MISD-NET-FW001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Firewall for security training',
                'deployment_date' => '2023-04-05',
                'last_maintenance' => '2024-04-05',
            ],

            // MISD Research Laboratory Inventory
            [
                'laboratory_id' => 5,
                'asset_tag' => 'MISD-RES-001',
                'computer_name' => 'MISD-RES-WS001',
                'lab_pc_num' => 'RES-001',
                'category' => 'Desktop',
                'processor' => 'Intel Core i9-13900K',
                'motherboard' => 'Dell Precision 5860',
                'video_card' => 'NVIDIA RTX 4070',
                'dvd_rom' => null,
                'psu' => '1000W',
                'ram' => '64GB DDR5',
                'storage' => '2TB NVMe SSD',
                'serial_number' => 'DL-MISD-RES-WS001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'High-performance workstation for R&D',
                'deployment_date' => '2023-07-12',
                'last_maintenance' => '2024-07-12',
            ],
            [
                'laboratory_id' => 5,
                'asset_tag' => 'MISD-RES-002',
                'computer_name' => 'MISD-RES-WS002',
                'lab_pc_num' => 'RES-002',
                'category' => 'Desktop',
                'processor' => 'Intel Core i9-13900K',
                'motherboard' => 'Dell Precision 5860',
                'video_card' => 'NVIDIA RTX 4070',
                'dvd_rom' => null,
                'psu' => '1000W',
                'ram' => '64GB DDR5',
                'storage' => '2TB NVMe SSD',
                'serial_number' => 'DL-MISD-RES-WS002',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'High-performance workstation for R&D',
                'deployment_date' => '2023-07-12',
                'last_maintenance' => '2024-07-12',
            ],

            // MISD Training Laboratory Inventory
            [
                'laboratory_id' => 6,
                'asset_tag' => 'MISD-TRN-001',
                'computer_name' => 'MISD-TRN-LP001',
                'lab_pc_num' => 'TRN-001',
                'category' => 'Laptop',
                'processor' => 'Intel Core i5-1335U',
                'motherboard' => 'Lenovo ThinkPad T14',
                'video_card' => 'Intel Iris Xe',
                'dvd_rom' => null,
                'psu' => 'Internal Battery',
                'ram' => '16GB DDR4',
                'storage' => '512GB NVMe SSD',
                'serial_number' => 'LV-MISD-TRN-LP001',
                'status' => 'Available',
                'condition' => 'Good',
                'notes' => 'Training laptop for workshops',
                'deployment_date' => '2023-08-15',
                'last_maintenance' => '2024-08-15',
            ],
            [
                'laboratory_id' => 6,
                'asset_tag' => 'MISD-TRN-002',
                'computer_name' => 'MISD-TRN-LP002',
                'lab_pc_num' => 'TRN-002',
                'category' => 'Laptop',
                'processor' => 'Intel Core i5-1335U',
                'motherboard' => 'Lenovo ThinkPad T14',
                'video_card' => 'Intel Iris Xe',
                'dvd_rom' => null,
                'psu' => 'Internal Battery',
                'ram' => '16GB DDR4',
                'storage' => '512GB NVMe SSD',
                'serial_number' => 'LV-MISD-TRN-LP002',
                'status' => 'Available',
                'condition' => 'Good',
                'notes' => 'Training laptop for workshops',
                'deployment_date' => '2023-08-15',
                'last_maintenance' => '2024-08-15',
            ],

            // MISD Server Room Inventory
            [
                'laboratory_id' => 7,
                'asset_tag' => 'MISD-SRV-001',
                'computer_name' => 'MISD-SRV-MAIN001',
                'lab_pc_num' => 'SRV-001',
                'category' => 'Server',
                'processor' => 'Intel Xeon Gold 6330Y',
                'motherboard' => 'Dell PowerEdge R750',
                'video_card' => 'Matrox G200eR3',
                'dvd_rom' => null,
                'psu' => '1600W Redundant',
                'ram' => '128GB DDR4 ECC',
                'storage' => '8x 4TB SAS HDD RAID 6',
                'serial_number' => 'DL-MISD-SRV-MAIN001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Main production server',
                'deployment_date' => '2023-02-01',
                'last_maintenance' => '2024-02-01',
            ],
            [
                'laboratory_id' => 7,
                'asset_tag' => 'MISD-SRV-002',
                'computer_name' => 'MISD-SRV-BACKUP001',
                'lab_pc_num' => 'SRV-002',
                'category' => 'Server',
                'processor' => 'Intel Xeon Gold 6330Y',
                'motherboard' => 'Dell PowerEdge R750',
                'video_card' => 'Matrox G200eR3',
                'dvd_rom' => null,
                'psu' => '1600W Redundant',
                'ram' => '128GB DDR4 ECC',
                'storage' => '8x 4TB SAS HDD RAID 6',
                'serial_number' => 'DL-MISD-SRV-BACKUP001',
                'status' => 'Deployed',
                'condition' => 'Excellent',
                'notes' => 'Backup server',
                'deployment_date' => '2023-02-01',
                'last_maintenance' => '2024-02-01',
            ],
        ];

        foreach ($inventoryItems as $item) {
            LaboratoryInventory::create($item);
        }

        $this->command->info('MISD laboratory inventory seeded successfully!');
    }
}